// Options page script
document.addEventListener('DOMContentLoaded', async () => {
  await loadSettings();
  setupEventListeners();
  displaySyncInfo();
});

async function loadSettings() {
  try {
    const result = await chrome.storage.sync.get('settings');
    const settings = result.settings || getDefaultSettings();

    document.getElementById('autoGenerateDescriptions').checked = settings.autoGenerateDescriptions;
    document.getElementById('apiProvider').value = settings.apiProvider || 'none';
    document.getElementById('apiKey').value = settings.apiKey || '';
    document.getElementById('enableSemanticSearch').checked = settings.enableSemanticSearch;
  } catch (error) {
    console.error('Error loading settings:', error);
  }
}

function getDefaultSettings() {
  return {
    autoGenerateDescriptions: true,
    apiProvider: 'none',
    apiKey: '',
    enableSemanticSearch: true,
    lastSyncDate: null
  };
}

function setupEventListeners() {
  document.getElementById('saveBtn').addEventListener('click', saveSettings);
  document.getElementById('resetBtn').addEventListener('click', resetSettings);
  document.getElementById('toggleApiKey').addEventListener('click', toggleApiKeyVisibility);
}

async function saveSettings() {
  try {
    const settings = {
      autoGenerateDescriptions: document.getElementById('autoGenerateDescriptions').checked,
      apiProvider: document.getElementById('apiProvider').value,
      apiKey: document.getElementById('apiKey').value,
      enableSemanticSearch: document.getElementById('enableSemanticSearch').checked,
      lastSyncDate: null // Will be set during sync
    };

    await chrome.storage.sync.set({ settings });

    showStatus('Settings saved successfully!', 'success');
  } catch (error) {
    console.error('Error saving settings:', error);
    showStatus('Error saving settings: ' + error.message, 'error');
  }
}

async function resetSettings() {
  if (confirm('Are you sure you want to reset all settings to defaults?')) {
    try {
      const settings = getDefaultSettings();
      await chrome.storage.sync.set({ settings });
      await loadSettings();
      showStatus('Settings reset to defaults', 'success');
    } catch (error) {
      console.error('Error resetting settings:', error);
      showStatus('Error resetting settings: ' + error.message, 'error');
    }
  }
}

function toggleApiKeyVisibility() {
  const apiKeyInput = document.getElementById('apiKey');
  const toggleBtn = document.getElementById('toggleApiKey');

  if (apiKeyInput.type === 'password') {
    apiKeyInput.type = 'text';
    toggleBtn.textContent = '🙈';
  } else {
    apiKeyInput.type = 'password';
    toggleBtn.textContent = '👁️';
  }
}

async function displaySyncInfo() {
  try {
    const result = await chrome.storage.sync.get('settings');
    const settings = result.settings || {};
    const syncInfoDiv = document.getElementById('syncInfo');

    if (settings.lastSyncDate) {
      const date = new Date(settings.lastSyncDate);
      syncInfoDiv.innerHTML = `
        <strong>Last sync:</strong> ${date.toLocaleString()}<br>
        <button class="btn" style="margin-top: 10px;" id="syncNowBtn">Sync Now</button>
      `;

      document.getElementById('syncNowBtn').addEventListener('click', async () => {
        syncInfoDiv.innerHTML = 'Syncing...';
        try {
          const result = await chrome.runtime.sendMessage({ action: 'syncBookmarks' });
          if (result.success) {
            showStatus(`Successfully synced ${result.count} bookmarks!`, 'success');
            await displaySyncInfo();
          } else {
            showStatus('Error syncing: ' + result.error, 'error');
          }
        } catch (error) {
          showStatus('Error syncing: ' + error.message, 'error');
        }
      });
    } else {
      syncInfoDiv.innerHTML = `
        <p>No sync performed yet.</p>
        <button class="btn" style="margin-top: 10px;" id="syncNowBtn">Sync Now</button>
      `;

      document.getElementById('syncNowBtn').addEventListener('click', async () => {
        syncInfoDiv.innerHTML = 'Syncing...';
        try {
          const result = await chrome.runtime.sendMessage({ action: 'syncBookmarks' });
          if (result.success) {
            showStatus(`Successfully synced ${result.count} bookmarks!`, 'success');
            await displaySyncInfo();
          } else {
            showStatus('Error syncing: ' + result.error, 'error');
          }
        } catch (error) {
          showStatus('Error syncing: ' + error.message, 'error');
        }
      });
    }
  } catch (error) {
    console.error('Error displaying sync info:', error);
  }
}

function showStatus(message, type) {
  const statusDiv = document.getElementById('statusMessage');
  const className = type === 'success' ? 'alert-success' : 'alert-error';

  statusDiv.innerHTML = `<div class="alert ${className}">${message}</div>`;

  setTimeout(() => {
    statusDiv.innerHTML = '';
  }, 5000);
}
