<script lang="ts">
  import type { ExtensionSettings, SyncResult } from '../types';

  let settings = $state<ExtensionSettings>({
    autoGenerateDescriptions: true,
    apiProvider: 'none',
    apiKey: '',
    enableSemanticSearch: true,
    lastSyncDate: null,
  });

  let showApiKey = $state(false);
  let statusMessage = $state<{ message: string; type: 'success' | 'error' } | null>(
    null
  );
  let syncInfo = $state<string>('Loading sync information...');
  let syncing = $state(false);

  // Load settings on mount
  $effect(() => {
    loadSettings();
    loadSyncInfo();
  });

  async function loadSettings() {
    try {
      const result = await chrome.storage.sync.get('settings');
      if (result.settings) {
        settings = result.settings;
      }
    } catch (error) {
      console.error('Error loading settings:', error);
    }
  }

  async function loadSyncInfo() {
    try {
      const result = await chrome.storage.sync.get('settings');
      const savedSettings: ExtensionSettings = result.settings || {};

      if (savedSettings.lastSyncDate) {
        const date = new Date(savedSettings.lastSyncDate);
        syncInfo = `Last sync: ${date.toLocaleString()}`;
      } else {
        syncInfo = 'No sync performed yet.';
      }
    } catch (error) {
      console.error('Error loading sync info:', error);
      syncInfo = 'Error loading sync info';
    }
  }

  async function saveSettings() {
    try {
      await chrome.storage.sync.set({ settings });
      showStatus('Settings saved successfully!', 'success');
    } catch (error) {
      showStatus(
        `Error saving settings: ${error instanceof Error ? error.message : 'Unknown error'}`,
        'error'
      );
    }
  }

  async function resetSettings() {
    if (confirm('Are you sure you want to reset all settings to defaults?')) {
      settings = {
        autoGenerateDescriptions: true,
        apiProvider: 'none',
        apiKey: '',
        enableSemanticSearch: true,
        lastSyncDate: null,
      };

      try {
        await chrome.storage.sync.set({ settings });
        showStatus('Settings reset to defaults', 'success');
      } catch (error) {
        showStatus(
          `Error resetting settings: ${error instanceof Error ? error.message : 'Unknown error'}`,
          'error'
        );
      }
    }
  }

  async function syncNow() {
    syncing = true;
    try {
      const result: SyncResult = await chrome.runtime.sendMessage({
        action: 'syncBookmarks',
      });

      if (result.success) {
        showStatus(`Successfully synced ${result.count} bookmarks!`, 'success');
        await loadSyncInfo();
      } else {
        showStatus(`Error syncing: ${result.error}`, 'error');
      }
    } catch (error) {
      showStatus(
        `Error syncing: ${error instanceof Error ? error.message : 'Unknown error'}`,
        'error'
      );
    } finally {
      syncing = false;
    }
  }

  function showStatus(message: string, type: 'success' | 'error') {
    statusMessage = { message, type };
    setTimeout(() => {
      statusMessage = null;
    }, 5000);
  }

  function toggleApiKeyVisibility() {
    showApiKey = !showApiKey;
  }
</script>

<div class="container">
  <div class="header">
    <h1>⚙️ Settings</h1>
    <p>Configure your bookmark organizer preferences</p>
  </div>

  <div class="content">
    <div class="section">
      <div class="section-title">AI Description Generation</div>

      <div class="info-box">
        <h4>About AI Descriptions</h4>
        <p>
          The extension can automatically generate descriptions for your bookmarks
          using AI. This requires an API key from OpenAI or Anthropic. If you
          don't provide an API key, you can still use the extension but
          descriptions will need to be added manually.
        </p>
      </div>

      <div class="form-group">
        <div class="checkbox-group">
          <input
            type="checkbox"
            id="autoGenerateDescriptions"
            bind:checked={settings.autoGenerateDescriptions}
          />
          <label for="autoGenerateDescriptions">
            Automatically generate descriptions for new bookmarks
          </label>
        </div>
      </div>

      <div class="form-group">
        <label for="apiProvider">AI Provider</label>
        <select id="apiProvider" bind:value={settings.apiProvider}>
          <option value="none">None (Manual descriptions only)</option>
          <option value="openai">OpenAI (GPT-3.5/GPT-4)</option>
          <option value="anthropic">Anthropic (Claude)</option>
        </select>
      </div>

      <div class="form-group">
        <label for="apiKey">API Key</label>
        <div class="api-key-input">
          <input
            type={showApiKey ? 'text' : 'password'}
            id="apiKey"
            bind:value={settings.apiKey}
            placeholder="Enter your API key"
          />
          <span
            class="toggle-visibility"
            onclick={toggleApiKeyVisibility}
            role="button"
            tabindex="0"
          >
            {showApiKey ? '🙈' : '👁️'}
          </span>
        </div>
        <div class="help-text">
          Your API key is stored locally and never sent anywhere except to the AI
          provider.
        </div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Search Settings</div>

      <div class="form-group">
        <div class="checkbox-group">
          <input
            type="checkbox"
            id="enableSemanticSearch"
            bind:checked={settings.enableSemanticSearch}
          />
          <label for="enableSemanticSearch">
            Enable semantic search (experimental)
          </label>
        </div>
        <div class="help-text">
          Semantic search uses AI to understand the meaning of your queries, not
          just keywords.
        </div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Sync Information</div>

      <div class="sync-info">{syncInfo}</div>

      <button class="btn" onclick={syncNow} disabled={syncing}>
        {syncing ? 'Syncing...' : 'Sync Now'}
      </button>
    </div>

    <div class="button-group">
      <button class="btn" onclick={saveSettings}>Save Settings</button>
      <button class="btn btn-secondary" onclick={resetSettings}>
        Reset to Defaults
      </button>
    </div>

    {#if statusMessage}
      <div class="alert alert-{statusMessage.type}">
        {statusMessage.message}
      </div>
    {/if}
  </div>
</div>

<style>
  .container {
    max-width: 800px;
    margin: 0 auto;
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
    overflow: hidden;
  }

  .header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 30px;
  }

  .header h1 {
    font-size: 28px;
    margin: 0 0 10px 0;
  }

  .header p {
    opacity: 0.9;
    font-size: 14px;
    margin: 0;
  }

  .content {
    padding: 30px;
  }

  .section {
    margin-bottom: 30px;
    padding-bottom: 30px;
    border-bottom: 1px solid #e0e0e0;
  }

  .section:last-of-type {
    border-bottom: none;
  }

  .section-title {
    font-size: 18px;
    font-weight: 600;
    color: #333;
    margin-bottom: 15px;
  }

  .form-group {
    margin-bottom: 20px;
  }

  label {
    display: block;
    font-size: 14px;
    font-weight: 500;
    color: #555;
    margin-bottom: 8px;
  }

  input[type='text'],
  input[type='password'],
  select {
    width: 100%;
    padding: 10px 15px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 14px;
    transition: border-color 0.3s;
  }

  input:focus,
  select:focus {
    outline: none;
    border-color: #667eea;
  }

  .checkbox-group {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .checkbox-group label {
    margin: 0;
  }

  input[type='checkbox'] {
    width: 18px;
    height: 18px;
    cursor: pointer;
  }

  .help-text {
    font-size: 12px;
    color: #999;
    margin-top: 5px;
  }

  .btn {
    background: #667eea;
    color: white;
    border: none;
    padding: 12px 24px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 14px;
    font-weight: 500;
    transition: background 0.3s;
  }

  .btn:hover:not(:disabled) {
    background: #5568d3;
  }

  .btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .btn-secondary {
    background: #e0e0e0;
    color: #333;
    margin-left: 10px;
  }

  .btn-secondary:hover {
    background: #d0d0d0;
  }

  .button-group {
    display: flex;
    align-items: center;
    margin-bottom: 20px;
  }

  .alert {
    padding: 12px 16px;
    border-radius: 6px;
    font-size: 14px;
  }

  .alert-success {
    background: #d4edda;
    color: #155724;
    border: 1px solid #c3e6cb;
  }

  .alert-error {
    background: #f8d7da;
    color: #721c24;
    border: 1px solid #f5c6cb;
  }

  .info-box {
    background: #e7f3ff;
    border-left: 4px solid #2196f3;
    padding: 15px;
    border-radius: 4px;
    margin-bottom: 20px;
  }

  .info-box h4 {
    margin: 0 0 8px 0;
    color: #1976d2;
  }

  .info-box p {
    font-size: 13px;
    color: #555;
    line-height: 1.5;
    margin: 0;
  }

  .api-key-input {
    position: relative;
  }

  .toggle-visibility {
    position: absolute;
    right: 15px;
    top: 50%;
    transform: translateY(-50%);
    cursor: pointer;
    user-select: none;
  }

  .sync-info {
    color: #666;
    font-size: 14px;
    margin-bottom: 10px;
  }
</style>
