// Type definitions for bookmark organizer extension

export interface Bookmark {
  id: string;
  url: string;
  title: string;
  dateAdded?: number;
  parentId?: string;
  index?: number;
  children?: Bookmark[];
}

export interface EnhancedBookmarkData {
  id: string;
  url: string;
  title: string;
  dateAdded: number;
  description: string;
  tags: string[];
  category: string;
  embedding: number[] | null;
  lastProcessed: number;
}

export interface ExtensionSettings {
  autoGenerateDescriptions: boolean;
  apiProvider: 'none' | 'openai' | 'anthropic';
  apiKey: string;
  enableSemanticSearch: boolean;
  lastSyncDate: number | null;
}

export interface BookmarkWithEnhanced extends Bookmark {
  enhanced: EnhancedBookmarkData | null;
}

export interface SyncResult {
  success: boolean;
  count?: number;
  error?: string;
}

export interface SearchResult {
  bookmark: BookmarkWithEnhanced;
  similarity?: number;
}

export type MessageAction =
  | 'getAllBookmarks'
  | 'syncBookmarks'
  | 'searchBookmarks'
  | 'generateDescription';

export interface Message {
  action: MessageAction;
  query?: string;
  bookmarkId?: string;
}

export interface MessageResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

// API Types
export interface OpenAIMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface OpenAIRequest {
  model: string;
  messages: OpenAIMessage[];
  max_tokens?: number;
  temperature?: number;
}

export interface OpenAIResponse {
  choices: Array<{
    message: {
      content: string;
    };
  }>;
}

export interface AnthropicMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface AnthropicRequest {
  model: string;
  messages: AnthropicMessage[];
  max_tokens: number;
}

export interface AnthropicResponse {
  content: Array<{
    text: string;
  }>;
}

// Chrome API augmentations
declare global {
  namespace chrome.bookmarks {
    interface BookmarkTreeNode {
      id: string;
      parentId?: string;
      index?: number;
      url?: string;
      title: string;
      dateAdded?: number;
      dateGroupModified?: number;
      children?: BookmarkTreeNode[];
    }
  }
}
